FROM nginx:alpine@sha256:4a73073bd557c65b759505da037898b61f1be6cbcc3c2c3aeac22d2a470c1752
COPY index.html /usr/share/nginx/html/index.html
COPY deploy/nginx-docker.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
