version: 2
updates:
  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ['dependencies', 'python']
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: pip
    directory: /sdks/python
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: ['dependencies', 'python', 'sdk']

  - package-ecosystem: npm
    directory: /sdks/typescript
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: ['dependencies', 'typescript', 'sdk']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: ['dependencies', 'ci']
